name: Security Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk:
    name: Snyk Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@v1
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}  # Store your Snyk token in GitHub secrets

      - name: Run Snyk test
        run: snyk test

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Store your SonarQube token in GitHub secrets
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://your-sonarqube-server \
            -Dsonar.login=$SONAR_TOKEN
